- name: Install Nginx with content and loop on RedHat-like and Debian-like systems 
  hosts: all
  become: true
  
  vars:
    source_folder: "../website_content2"  # устанавливаем директорию, откуда будем копировать
    dest_folder_debian: "/var/www/html" # Путь назначения для дефолтной страницы на Debian-подобных системах
    dest_folder_redhat: "/usr/share/nginx/html" # Путь назначения для дефолтной страницы на RedHat-подобных системах
    web_files: # Определяем элементы цикла в виде переменной web_files
      - index.html
      - image1.jpeg
      - image2.png

  tasks:
    - name: Ensure the Nginx package is installed 
      package: 
        name: nginx
        state: present
        update_cache: yes 

    - name: Copy custom index.html to Nginx web root on Debian-like systems
      copy: 
        src: "{{ source_folder }}/{{ item }}"  #  откуда брать файл
        dest: "{{ dest_folder_debian }}"   #  каталог куда копировать файл
        mode: '0644' 
      loop: "{{ web_files }}"  # задаем какие элементы копировать в цикле
      when: ansible_os_family == "Debian"

    - name: Copy custom index.html to Nginx web root on RedHat-like systems
      copy: 
        src: "{{ source_folder }}/{{ item }}"  #  откуда брать файл
        dest: "{{ dest_folder_redhat }}"   #  каталог куда копировать файл
        mode: '0644' 
      loop: "{{ web_files }}" # задаем какие элементы копировать в цикле
      when: ansible_os_family == "RedHat"

    - name: Ensure nginx is running and enabled 
      service: name=nginx state=started enabled=yes